title: Avishai's CTF Writeups
description: "Yalla Balagan! A collection of my CTF writeups and solutions."
url: "https://avishaigonen123.github.io"
baseurl: "/CTF_writeups"  
remote_theme: pages-themes/hacker
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc: true
  toc_levels: 1..3

  
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-copy-button
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-cards
  - jekyll-tags
  - jekyll-social-share-buttons
  - jekyll-redirect-from


# SEO Configuration
seo:
  description: "Avishai's CTF Writeups - A collection of writeups, challenges, and solutions from CTFs."
  keywords:
    - "CTF"
    - "writeups"
    - "security"
    - "hacking"
  image: "/favicon.ico" # Set a default image for social media

# Define categories in your _config.yml
categories:
  - "Web Exploitation"
  - "Crypto"
  - "Binary Exploitation"
  

paginate: 10
paginate_path: "/page:num/"

# ðŸ§  ADD THIS SECTION ðŸ‘‡
include:
  - overthewire
  - pwnable.kr
  - ringzer0
  - pwnable.tw
  - hackthebox
  - tryhackme
  - picoctf
  - webhacking.kr
  - lord-of-sql-injection
  - trythis0ne
  - AppSec-IL-2025
  - websec.fr
  - root-me

  - assets/  